### ISSUE TITLE
sparkassen broker deka

### ISSUE THREAD

**Issue by codeofsumit** [tresorone/tresor-import#1017]
## Description
> fehler lautet einfach dass das pdf nicht erkannt ist, bzw. unbekannt ist.

## Document
<details><summary>aaaaaaaaaa.pdf</summary><p>

```json
[
  [
    "S Broker Depot",
    "https://depot.sbroker.de/trading/ordermanager",
    "1 von 2",
    "15.01.2021, 22:00"
  ],
  [
    "S Broker Depot",
    "https://depot.sbroker.de/trading/ordermanager",
    "2 von 2",
    "15.01.2021, 22:00"
  ]
]

```

</p></details>

---
Issue submitted with https://import.tresor.one

**Comment by dredav** [comment]
This is not a valid document
