### ISSUE TITLE
Degiro Export

### ISSUE THREAD

**Issue by codeofsumit** [tresorone/tresor-import#1207]
## Description
> Hallo, ich wollte aus Degiro exportieren und bei euch importieren. 

## Document
<details><summary>Portfolio.pdf</summary><p>

```json
[
  [
REDACTED  ]
]

```

</p></details>

---
Issue submitted with https://import.tresor.one

**Comment by RoadrunnerDE** [comment]
please delete the PDF

**Comment by SirGibihm** [comment]
@RoadrunnerDE DEleted as per your request
