### ISSUE TITLE
Degiro Import

### ISSUE THREAD

**Issue by codeofsumit** [tresorone/tresor-import#1209]
## Description
> Hallo, das scheinen wohl die richtigen Daten zu sein, diese lassen sich aber genau so wenig importieren

## Document
<details><summary>Transactions (3).pdf</summary><p>

```json
[REDACTED]
```

</p></details>

---
Issue submitted with https://import.tresor.one

**Comment by RoadrunnerDE** [comment]
please delete the PDF

**Comment by SirGibihm** [comment]
The .PDF has been deleted as requested. I briefly checked through the file beforehand: Currently the transaction-logs are not supported for DeGiro. Please use the individual Buy/Sell/Dividend Documents as they can be parsed. We might add support for this kind of document down the road but currently there are still some technical issues to be resolved.
