### ISSUE TITLE
[Commerzbank] Buy of apple not being parsed

### ISSUE THREAD

**Issue by codeofsumit** [tresorone/tresor-import#1225]
## Description
> Um mein Portfolie etwas besser zu visualisieren und einen besseren Überblick über mein Investment zu haben, möchte ich gerne auf dieser Plattform die Werte meines Commerzbank-Depot einpflegen.

## Document
<details><summary>Apple 2.pdf</summary><p>

```json
[
  [
    "Umsatzdetails",
    "Max Mustermann",
    "www.commerzbank.de",
    "Download am",
    "25. Januar 2021, 16:29 Uhr",
    "Seite",
    "1",
    "/",
    "1",
    "IBAN:",
    "DE86 5904 0000 0573 2953 00  |  BIC COBADEFFXXX",
    "Kontonummer:",
    "573295300 | BLZ 59040000",
    "Kontowährung:",
    "EUR",
    "Kontoinhaber:",
    "Max Mustermann",
    "Buchungstag:",
    "16.06.2020",
    "Buchungstext:",
    "WP-KAUF GESCH.TG.15.06.2020",
    "V. 15.06.2020 77/001858",
    "APPLE INC.",
    "WPKNR: 865985 ISIN: US0378331005",
    "NENNWERT: 2,000",
    "GESCH.-NR: 000148300715/001",
    "Wertstellung:",
    "17.06.2020",
    "Betrag:",
    "- 601,30 EUR"
  ]
]

```

</p></details>

---
Issue submitted with https://import.tresor.one

**Comment by apentermann** [comment]
Werde mich mal dran versuchen.

**Comment by apentermann** [comment]
Hallo zusammen,

ich bin gerade dabei die neuen Felder zu hinterlegen.

Ich stolpere etwas über folgende Zeile: https://github.com/tresorone/tresor-import/blob/a906cbf9c608ec6c117a2075dd0dcdd112a927af/src/brokers/commerzbank.js#L29-L33

Laut dem Quelldokument sind keine Stücke ausgewiesen. Meine Vermutung war dann, dass es sich um das Feld **NENNWERT** handelt, jedoch passt die Rechnung dann nicht ( 2 x 84,21 € sind nicht 601,30 - wie unter **Betrag** zu sehen).

Ist eventuell die Stückzahl gar nicht hinterlegt und was passiert dann in einem solchen Fall?

**Comment by SirGibihm** [comment]
@apentermann hmm. Für mich sieht das Dokument nicht nach einem normalen Commerzbank Dokument aus sondern eher nach einer Art Kontoauszugm, siehe zum Beispiel einen Kauf: https://github.com/tresorone/tresor-import/blob/master/tests/brokers/__mocks__/commerzbank/buy/buy_mixed_A1JX51_1.json. Daher würde ich an dieser Stelle erstmal sagen, dass wir das Dokument nicht parsen wollen (und können). Damit diese Art Dokument nun "richtig" verarbeitet werden kann sollte man es als `ignoredDocument` klassifizieren und Status code 7 müsste zurückgegeben werden, siehe https://github.com/tresorone/tresor-import/blob/master/docs/status_code.md

**Comment by apentermann** [comment]
@SirGibihm okay, dann passe ich den Code so an. Melde mich dann wenn es fertig ist.
