### ISSUE TITLE
[Portfolio performance] urlaub

### ISSUE THREAD

**Issue by codeofsumit** [tresorone/tresor-import#1323]
## Description
> 1

## Document
<details><summary>Urlaub.csv</summary><p>

```text
Xxxxx;Xxx;Xxxx;Xxxxxxxxxäxxxxx;Xxxxxxx;Xxüxx;XXXX;XXX;Xxxxxx-Xxxxxx;Xxxxxxxxxxxxxx;Xxxxx
0000-00-00X00:00;Xxxxxxx;000,00;XXX;;;;;;;

```

</p></details>

## Community profile

1

---
Issue submitted with https://import.tresor.one

**Comment by dredav** [comment]
This document is to much anonymized. Can't contact the user.
