### ISSUE TITLE
[Commerzbank] Werkpapierverkauf kann nicht importiert werden

### ISSUE THREAD

**Issue by codeofsumit** [tresorone/tresor-import#1470]
## Description
> Der Wertpapierverkauf kann nicht importiert werden. Verkauft wurde der DWS I n v . - ESG E q u i t y Income für 47,80

## Document
<details><summary>Wertpapierdokument_577844400_20210204 (1).pdf</summary><p>

```json
[
  [
    "Ihren",
    "Auftrag",
    "haben",
    "wir",
    "gemäß",
    "unseren",
    "Sonderbedingungen",
    "für",
    "Wertpapiergeschäfte",
    "wie",
    "nachstehend",
    "ausgeführt.",
    "Die",
    "Wertpapiere",
    "haben",
    "wir",
    "der",
    "Abrechnung",
    "entsprechend",
    "gebucht.",
    "Wir",
    "bitten",
    "Sie,",
    "diese",
    "Abrechnung",
    "auf",
    "ihre",
    "Richtigkeit",
    "und",
    "Vollständigkeit",
    "zu",
    "XXXXXX",
    "überprüfen",
    "und",
    "etwaige",
    "Einwendungen",
    "unverzüglich",
    "zu",
    "erheben.",
    "40300",
    "DUESSELDORF",
    "Telefon",
    ":",
    "02421",
    "183-0",
    "Filnr:",
    "000",
    "00000",
    "000",
    "Depotnr.:",
    "0000000",
    "00",
    "BLZ:",
    "000",
    "000",
    "00",
    "Xxxxx",
    "Xxxxxxxx",
    "Xxxxxxx",
    "Xxxxxxxx",
    "00",
    "00000",
    "Xxxxxxx",
    "GESCHÄFTSABRECHNUNG",
    "VOM",
    "04.02.2021",
    "für",
    "Ihr",
    "StartDepot",
    "*",
    "Wertpapierverkauf",
    "Geschäftsnummer",
    ":",
    "00",
    "000000",
    "000000000000-000",
    "Rechnungsnummer",
    ":",
    "000000000000X000",
    "Geschäftstag",
    ":",
    "04.02.2021",
    "Abwicklung",
    ":",
    "Rückgabe",
    "Handelszeit",
    ":",
    "19:59",
    "Uhr",
    "(MEZ/MESZ)",
    "Wertpapier-Bezeichnung",
    "Wertpapierkennnummer",
    "DWS",
    "Inv.-",
    "ESG",
    "Equity",
    "Income",
    "DWS2NY",
    "Inhaber-Anteile",
    "LD",
    "o.N.",
    "Nennwert",
    "Zum",
    "Preis",
    "von",
    "St.",
    "0,40",
    "EUR",
    "119,51",
    "Kurswert",
    ":",
    "EUR",
    "47,80",
    "IBAN",
    "Valuta",
    "Zu",
    "Ihren",
    "Gunsten",
    "vor",
    "Steuern",
    "XX00",
    "0000",
    "0000",
    "0000",
    "0000",
    "00",
    "EUR",
    "09.02.2021",
    "EUR",
    "47,80",
    "Verwahrungs-Art:",
    "GIROSAMMELDEPOT",
    "Ihre",
    "Wertpapier-Order",
    "wurde",
    "über",
    "das",
    "Online",
    "Banking",
    "erteilt.",
    "Diesem",
    "Wertpapiergeschäft",
    "ging",
    "keine",
    "individuelle",
    "Anlageempfehlung",
    "der",
    "Bank",
    "voraus.",
    "Informationen",
    "zur",
    "steuerlichen",
    "Behandlung",
    "dieses",
    "Geschäftsvorgangs",
    "und",
    "den",
    "auf",
    "Ihrem",
    "Konto",
    "gebuchten",
    "Endbetrag",
    "finden",
    "Sie",
    "auf",
    "der",
    "separaten",
    "Steuermitteilung.",
    "C",
    "O",
    "M",
    "M",
    "E",
    "R",
    "Z",
    "B",
    "A",
    "N",
    "K",
    "Aktiengesellschaft",
    "Diese",
    "Abrechnung",
    "wird",
    "von",
    "der",
    "Bank",
    "nicht",
    "unterschrieben",
    "Die",
    "Leistung",
    "ist",
    "gemäß",
    "§4",
    "Nr.8",
    "UStG",
    "umsatzsteuerfrei.",
    "USt-Id-Nr.:",
    "DE",
    "000",
    "000",
    "000",
    "X000",
    "XX000X/00/00/0000"
  ]
]

```

</p></details>

## Community profile

https://community.tresor.one/u/45380eed

---
Issue submitted with https://import.tresor.one

**Comment by apentermann** [comment]
@dredav @SirGibihm Hier ist es ja recht eindeutig, dass der Verkaufsweg noch fehlt. Kann ich in solchen Fällen direkt mit der Bearbeitung anfangen oder soll ich mich immer erst mit euch abstimmen?

**Comment by SirGibihm** [comment]
> @dredav @SirGibihm Hier ist es ja recht eindeutig, dass der Verkaufsweg noch fehlt. Kann ich in solchen Fällen direkt mit der Bearbeitung anfangen oder soll ich mich immer erst mit euch abstimmen?

Du kannst das issue gerne einfach übernehmen ohne Rücksprache. Assign dich ggf selbst Bzw schreib einen Kommentar, damit es nicht doppelt bearbeitet wird. Wenn du dann einen Pull request stellst tag einfach David oder mich als Reviewer

**Comment by apentermann** [comment]
@SirGibihm 
Wenn du mal Zeit findest, könntest du bitte einmal folgenden Commit anschauen (https://github.com/apentermann/tresor-import/commit/88419d0a2ea5ff5a42a5b347505f5df328ab245e)?
Nach diesen Änderungen schlagen zwei andere Banken beim Testen fehl (siehe Kommentar).
Kannst du mir einen Tipp geben, wo ich was falsch gemacht habe, da ich diese Dateien garnicht verändert hatte?

**Comment by SirGibihm** [comment]
Ich schau heute Abend drüber!

**Comment by SirGibihm** [comment]
> 
> 
> @SirGibihm
> Wenn du mal Zeit findest, könntest du bitte einmal folgenden Commit anschauen ([apentermann@88419d0](https://github.com/apentermann/tresor-import/commit/88419d0a2ea5ff5a42a5b347505f5df328ab245e))?
> Nach diesen Änderungen schlagen zwei andere Banken beim Testen fehl (siehe Kommentar).
> Kannst du mir einen Tipp geben, wo ich was falsch gemacht habe, da ich diese Dateien garnicht verändert hatte?

Ich kann leider nicht in deinem Fork kommentieren aber der Fehler liegt in deiner  `src/brokers/commerzbank.js` in Zeile 384. Da hast du stehen: 
```javascript
detectedButIgnoredDocument(firstPageContent) || isSell(firstPageContent))
```

Du hast die `isSell()` Funktion in der falschen Klammer. Damit das Dokument als Kauf oder Dividende klassifiziert wird muss in dem Dokument der String `commerzbank` auftauchen. So wie du die Klammern um die Boolsche Logik gesetzt hast wird das aber nicht überprüft. 
Was da derzeit bei dir steht ist:  
Das Dokument ist .pdf UND [ **(** es enthält `commerzbank` ODER `SteuerlicheBehandlung...`) UND NICHT (enthält `comdirect` ODER enthält `onvista` ) UND (ist ein `Kauf` oder eine `Dividende`) **)** ODER  (ist eine Transaction Report ODER ist ein ignoriertes Dokuemnt **_ODER ist ein Verkauf_**) ]

Was da stehen müsste: 
Das Dokument ist .pdf UND [ **(** es enthält `commerzbank` ODER `SteuerlicheBehandlung...`) UND NICHT (enthält `comdirect` ODER enthält `onvista` ) UND (ist ein `Kauf` **_ODER ein Verkauf_** oder eine `Dividende`) **)** ODER  (ist eine Transaction Report ODER ist ein ignoriertes Dokuemnt ODER ist ein Verkauf) ]

Grade reicht die Bedingung *istPDF* UND *istVerkauf* aus. In Traderepublic Dokumenten ist auch zT der Begriff `Wertpapierverkauf` enthalten und auch das sind .pdf Dokumente. Daher sagen hier sowohl der Comerzbank parser UND der Traderepublic parser, dass sie das Dokument identifzieren können. Das sollte natürlich nie sein, denn so kann kein passender Parser zugewiesen werden

**Comment by apentermann** [comment]
Mich hatten die Fehler in den anderen Broker Dateien total verunsichert. Jetzt wo ich es lese ist es total logisch und nachvollziehbar. 

Vielen Dank für deine Zeit und für's debuggen. Werde mich direkt morgen dran machen und es hoffentlich nicht noch einmal übersehen.
