### ISSUE TITLE
onvista PDF import fehlgeschlagen

### ISSUE THREAD

**Issue by codeofsumit** [tresorone/tresor-import#148]
<h2>Description</h2>
<blockquote>
<p>Import fehlgeschlagen</p>
</blockquote>
<h2>Document</h2>
<details><summary>Depotbersicht_Wertpapiere_111020_1957.pdf.pdf</summary><p>
<pre><code class="language-json">[
  [
    &quot;Konto:&quot;,
    &quot;348295&quot;,
    &quot;User:&quot;,
    &quot;HK348295&quot;,
    &quot;Datum:&quot;,
    &quot;11.10.20 19:57:31&quot;,
    &quot;Depotübersicht Wertpapiere&quot;,
    &quot;Nominal&quot;,
    &quot;Stück&quot;,
    &quot;Name&quot;,
    &quot;WKN/ISIN&quot;,
    &quot;WP-Art&quot;,
    &quot;Datum&quot;,
    &quot;Zeit&quot;,
    &quot;Aktueller Kurs&quot;,
    &quot;Handelsplatz&quot;,
    &quot;Kaufkurs&quot;,
    &quot;Kaufwert&quot;,
    &quot;Gesamtperfor.&quot;,
    &quot;(abs/rel.)&quot;,
    &quot;Tagesperfor.&quot;,
    &quot;(abs/rel.)&quot;,
    &quot;Wert&quot;,
    &quot;Aktueller Wert&quot;,
    &quot;3&quot;,
    &quot;3M RG&quot;,
    &quot;851745 / US88579Y1010&quot;,
    &quot;Aktie&quot;,
    &quot;09.10.2020&quot;,
    &quot;19:50:24&quot;,
    &quot;143,0600 EUR&quot;,
    &quot;Düsseldorf&quot;,
    &quot;139,1200 EUR&quot;,
    &quot;417,36 EUR&quot;,
    &quot;11,82 EUR&quot;,
    &quot;2,83 %&quot;,
    &quot;1,2000 EUR&quot;,
    &quot;0,85 %&quot;,
    &quot;429,18 EUR&quot;,
    &quot;429,18 EUR&quot;,
    &quot;30&quot;,
    &quot;ALIBABA GRP RG&quot;,
    &quot;A2PVFU / KYG017191142&quot;,
    &quot;Aktie&quot;,
    &quot;09.10.2020&quot;,
    &quot;16:00:49&quot;,
    &quot;31,5400 EUR&quot;,
    &quot;Düsseldorf&quot;,
    &quot;30,5527 EUR&quot;,
    &quot;916,58 EUR&quot;,
    &quot;29,62 EUR&quot;,
    &quot;3,23 %&quot;,
    &quot;0,5600 EUR&quot;,
    &quot;1,81 %&quot;,
    &quot;946,20 EUR&quot;,
    &quot;946,20 EUR&quot;,
    &quot;4&quot;,
    &quot;APPLE RG&quot;,
    &quot;865985 / US0378331005&quot;,
    &quot;Aktie&quot;,
    &quot;09.10.2020&quot;,
    &quot;21:59:30&quot;,
    &quot;98,9500 EUR&quot;,
    &quot;Stuttgart&quot;,
    &quot;95,6125 EUR&quot;,
    &quot;382,45 EUR&quot;,
    &quot;13,35 EUR&quot;,
    &quot;3,49 %&quot;,
    &quot;1,0900 EUR&quot;,
    &quot;1,11 %&quot;,
    &quot;395,80 EUR&quot;,
    &quot;395,80 EUR&quot;,
    &quot;5&quot;,
    &quot;BEYOND MEAT RG&quot;,
    &quot;A2N7XQ / US08862E1091&quot;,
    &quot;Aktie&quot;,
    &quot;09.10.2020&quot;,
    &quot;19:55:52&quot;,
    &quot;162,3000 EUR&quot;,
    &quot;Stuttgart&quot;,
    &quot;145,8200 EUR&quot;,
    &quot;729,10 EUR&quot;,
    &quot;82,40 EUR&quot;,
    &quot;11,30 %&quot;,
    &quot;-1,7200 EUR&quot;,
    &quot;-1,05 %&quot;,
    &quot;811,50 EUR&quot;,
    &quot;811,50 EUR&quot;,
    &quot;50&quot;,
    &quot;BYD -H-&quot;,
    &quot;A0M4W9 / CNE100000296&quot;,
    &quot;Aktie&quot;,
    &quot;09.10.2020&quot;,
    &quot;21:50:57&quot;,
    &quot;13,7950 EUR&quot;,
    &quot;Stuttgart&quot;,
    &quot;11,9950 EUR&quot;,
    &quot;599,75 EUR&quot;,
    &quot;90,00 EUR&quot;,
    &quot;15,01 %&quot;,
    &quot;-0,4000 EUR&quot;,
    &quot;-2,82 %&quot;,
    &quot;689,75 EUR&quot;,
    &quot;689,75 EUR&quot;,
    &quot;10&quot;,
    &quot;CYBERARK SOFTWAR RG&quot;,
    &quot;A12CPP / IL0011334468&quot;,
    &quot;Aktie&quot;,
    &quot;09.10.2020&quot;,
    &quot;18:31:40&quot;,
    &quot;95,4800 EUR&quot;,
    &quot;Frankfurt&quot;,
    &quot;90,9650 EUR&quot;,
    &quot;909,65 EUR&quot;,
    &quot;45,15 EUR&quot;,
    &quot;4,96 %&quot;,
    &quot;0,6800 EUR&quot;,
    &quot;0,72 %&quot;,
    &quot;954,80 EUR&quot;,
    &quot;954,80 EUR&quot;,
    &quot;10&quot;,
    &quot;INTEL RG&quot;,
    &quot;855681 / US4581401001&quot;,
    &quot;Aktie&quot;,
    &quot;09.10.2020&quot;,
    &quot;20:46:59&quot;,
    &quot;44,6000 EUR&quot;,
    &quot;Stuttgart&quot;,
    &quot;41,8950 EUR&quot;,
    &quot;418,95 EUR&quot;,
    &quot;27,05 EUR&quot;,
    &quot;6,46 %&quot;,
    &quot;-0,6850 EUR&quot;,
    &quot;-1,51 %&quot;,
    &quot;446,00 EUR&quot;,
    &quot;446,00 EUR&quot;,
    &quot;8,0486&quot;,
    &quot;ISHA S&amp;P USD-AC&quot;,
    &quot;A142N1 / IE00B3WJKG14&quot;,
    &quot;ETF&quot;,
    &quot;09.10.2020&quot;,
    &quot;21:55:09&quot;,
    &quot;12,6740 EUR&quot;,
    &quot;Stuttgart&quot;,
    &quot;12,1760 EUR&quot;,
    &quot;98,00 EUR&quot;,
    &quot;4,01 EUR&quot;,
    &quot;4,09 %&quot;,
    &quot;0,0660 EUR&quot;,
    &quot;0,52 %&quot;,
    &quot;102,01 EUR&quot;,
    &quot;102,01 EUR&quot;,
    &quot;12,0204&quot;,
    &quot;ISHS AUT ETF USD-AC&quot;,
    &quot;A2ANH0 / IE00BYZK4552&quot;,
    &quot;ETF&quot;,
    &quot;09.10.2020&quot;,
    &quot;21:55:14&quot;,
    &quot;8,5210 EUR&quot;,
    &quot;Stuttgart&quot;,
    &quot;8,2360 EUR&quot;,
    &quot;99,00 EUR&quot;,
    &quot;3,43 EUR&quot;,
    &quot;3,46 %&quot;,
    &quot;0,0760 EUR&quot;,
    &quot;0,90 %&quot;,
    &quot;102,43 EUR&quot;,
    &quot;102,43 EUR&quot;,
    &quot;4,1283&quot;,
    &quot;ISHS GLB INFRA USD&quot;,
    &quot;A0LEW9 / IE00B1FZS467&quot;,
    &quot;ETF&quot;,
    &quot;09.10.2020&quot;,
    &quot;21:55:19&quot;,
    &quot;24,4700 EUR&quot;,
    &quot;Stuttgart&quot;,
    &quot;23,9808 EUR&quot;,
    &quot;99,00 EUR&quot;,
    &quot;2,02 EUR&quot;,
    &quot;2,04 %&quot;,
    &quot;-0,0400 EUR&quot;,
    &quot;-0,16 %&quot;,
    &quot;101,02 EUR&quot;,
    &quot;101,02 EUR&quot;,
    &quot;/&quot;,
    &quot;/&quot;,
    &quot;GESAMTSUMME&quot;,
    &quot;6.438,14 EUR&quot;,
    &quot;428,31 EUR&quot;,
    &quot;6,653 %&quot;,
    &quot;5,39 EUR&quot;,
    &quot;0,079 %&quot;,
    &quot;6.866,45 EUR&quot;,
    &quot;Powered by TCPDF (www.tcpdf.org)&quot;
  ]
]

</code></pre>
</p></details>
<h2>Community profile</h2>
<p>www.heikokolz.de</p>
<hr />
<p>Issue submitted with https://import.tresor.one</p>

**Comment by SirGibihm** [comment]
Bei dem Dokument handelt es sich nicht um eine Kauforder sondern den Inhalt eines Depots. Die Nutzer scheinen da nicht ganz die Art der zu importierenden Dokumente zu verstehen. Entweder wir fangen das im UI ab ODER wir schaffen eine Funktion, die basierend auf dem aktuellen Stand alle Wertpapiere importiert (natürlich hat man dann keinerlei historische Daten, da der errechnte Kauf am Datum des Reports liegt).

**Comment by dredav** [comment]
We implemented a similar import for Trade Republic for #98. 
If we have enough information we can handle this document to make an easy setup from his portfolio for the user. I think the type should not be `Buy` its more a `admission` (? -> Einlieferung), see the comment [here](https://github.com/codeofsumit/tresor-import/issues/166#issuecomment-712368924).

**Comment by dredav** [comment]
@SirGibihm Did you already code something for this issue or can I take this one?

**Comment by SirGibihm** [comment]
@dredav No, I didn't so go ahead
