### ISSUE TITLE
Multi-Currency Support - optional additions to parsing

### ISSUE THREAD

**Issue by codeofsumit** [tresorone/tresor-import#187]
Hi lovely contributors,

I'm working on multi-currency and foreign exchange support in Tresor One right now.
The concept is as follows:
* A portfolio has a base currency - `EUR` by default (not editable for now).
* A holding has an exchange and therefore currency for its prices selected
* An activity is bought in a specific currency

Tresor One will adjust prices from foreign exchanges (e.g. NASDAQ) automatically to the portfolios base currency so all calculations happen on the base currency.

Regarding activities, we set the requirement that all activities from a portfolio are stored in the base currency because adjusting them on the fly would be a huge performance overhead.

That means, when storing activities we expect the values are stored in the portfolios base currency.
Currently, that is always the case as german brokers give us the `amount` in EUR, even if it was purchased on a foreign exchange.
It also means when changing the base currency of a portfolio down the road, Tresor One will go through all activities and adjusts all values of an activity to the new base currency *and stores that in the database*. In that process, T1 will store additional information in an activity document: 
* `currency` which is always equal to the base currency
* `originalCurrency` the original currency that differs from the base currency
* `fxRate` the foreign currency exchange rate (fxRate) (e.g.EUR/USD) from the base currency to the original currency.

We fetch fxRates with the portfolios base currency as a base. So if we fetch an fxRate for an activity that was purchased in USD but the portfolio base currency is EUR, it will be

1 EUR = 1.234 USD
The fxRate is 1.234

The relationship is always 
`amount in base currency` * `fxRate` = `amount in original currency`

Proposal / optional ToDo:
Nothing *has to* change. But in order to give the user more information in the UI, we could store possible currency adjustments done by the brokers inside the parsed activities too. Specifically the `originalCurrency` and the `fxRate`. At least in comdirect PDFs, I know they are present.

This is a dividend payment:
![image](https://user-images.githubusercontent.com/2399810/97333951-6d147280-187c-11eb-9cb5-52406cca919b.png)

While `11,11 EUR` as the amount is totally sufficient - we could store additionally the used `fxRate: 1,140200` and the `originalCurrency: 'USD'`. This can then be used to show the user that the currency adjustment happened in the T1 UI.
And for testing: `amount (11,11 EUR) * fxRate (1,140200) = amount in original currency (12,67 USD)`.

This is not a requirement - just a nice to have. What are your thoughts?

Completely unrelated: I'm wondering about the 15% Quellensteuer in USD. Are we currently ignoring that? Or applying the `fxRate` to it to get a tax amount in EUR?

**Comment by dredav** [comment]
>I'm wondering about the 15% Quellensteuer in USD. Are we currently ignoring that? Or applying the fxRate to it to get a tax amount in EUR?

Yes for the most brokers we currently ignore the withholding taxes. Some broker has the withholding tax amount in EUR (eg. Baader Bank) and we use the tax amount some only in the foreign currency. Trade Republic has as the only broker currently the full fxRate conversion support for: withholding tax, price and third party fee. All other brokers are on my list (I need to create an issue to track the progress...)

**Comment by dredav** [comment]
With the fxRate from the document we can convert all values. So we should store the original value and the converted (and of course the fxRate). We have in a activity the following currency based fields: `price`, `amount`, `tax` and `fee`.

When the import logic convert the value for one of these four fields, I sugest to add an additional field with the name of the current one and the prefix `original` (e.g. price is 10 USD, fx 1.140200: We convert the value in price to the base currency EUR: 10 / 1,140200 ~ `8,77039116`, add field `fxRate` with `1.140200`, `originalCurrency` with `USD` and `originalPrice` with `10`.

This issue is related to #113. I will close #113 so we can handle the case here.

**Comment by SirGibihm** [comment]
> Yes for the most brokers we currently ignore the withholding taxes

We had lots of requests in the previous issues that demanded fixes for this which have been implemented to a certain degree. I don't think the situation is to bad but needs to be checked. Will do so tomorrow. 

Regarding Sumits suggestion, this seems to be a quite sensible thing to do. I could take care of this but since I need to touch ALL brokers currently implemented this just screams merge conflict. Thus I would prefer doing this after the current pull requests are all merged and I can't cause to much conflicts 🙈

**Comment by codeofsumit** [comment]
@SirGibihm I think the changes could be done sequentially to not create one huge Pull Request.
Additionally @dredav I don't think we need to store `originalPrice` and so on. The values in the "target currency" (in our case almost exclusively EUR) and the fxRate are enough. All original values can be calculated that way in the frontends - if required.

Regarding determination of the "target currency" I would like to propose to make this just as dynamic (=> read from the PDF) as the original currency.
Imagine a scenario where someone parses a PDF with a Buy activity of Nintendo at Tokio Exchange in YEN - done via a Broker whose cash account is in USD.
The values should be stored in USD, `fxRate` would be USD/YEN and `originalCurrency = USD`. Tresor One would then change values again to EUR during saving of the activity.
Thats my long way of saying, please don't hardcode "EUR" anywhere 😅 (if possible).

**Comment by SirGibihm** [comment]
I am currently implementing the activity fields `originalCurrency` and `fxRate` for the new broker implementationfor Erste Bank, see PullRequest #190 / Issue #188. What should the activity contain if there is no foreign currency/fx Rate as everything is in €? I suggest setting them to `undefined` in that case.

**Comment by codeofsumit** [comment]
> I am currently implementing the activity fields `originalCurrency` and `fxRate` for the new broker implementationfor Erste Bank, see PullRequest #190 / Issue #188. What should the activity contain if there is no foreign currency/fx Rate as everything is in €? I suggest setting them to `undefined` in that case.

Yes leave them undefined / don't add the field.

**Comment by SirGibihm** [comment]
List of current brokers/pullrequest meeting the criterias:
* [ ] 1822direct
* [ ] baaderBank
* [ ] comdirect - Partly, Buy and Dividend have it; Sells doesn't, see #194
* [ ] consorsbank
* [ ] dkb
* [ ] ersteBank - Partly, Buy has it, Dividend and Sells are not implemented yet #190 
* [ ] ebase (pdf) 
* [ ] flatex
* [ ] onvista
* [ ] postbank
* [ ] traderepublic

**Comment by dredav** [comment]
We need to adjust some broker implementations because they currently searching numbers by the currency symbol `EUR`. E.g. https://github.com/codeofsumit/tresor-import/blob/master/src/brokers/comdirect.js#L71

**Comment by SirGibihm** [comment]
> 
> 
> We need to adjust some broker implementations because they currently searching numbers by the currency symbol `EUR`. E.g. https://github.com/codeofsumit/tresor-import/blob/master/src/brokers/comdirect.js#L71

This has become a bad example as I removed all occurances of EUR for comdirect in #207 . Other brokers might still have hardcoded `EUR` values.

**Comment by SirGibihm** [comment]
Clsoing the issue as the Foreign Currencies are supported more and more + no tracking here is done
