### ISSUE TITLE
Deutsche Bank dokumente

### ISSUE THREAD

**Issue by codeofsumit** [tresorone/tresor-import#285]
## Description
> Deutsche Bank dokuemnte konnten nicht gelesen werden

## Documents
<details><summary>Dividendengutschrift-001.pdf</summary><p>

```json
[
  [],
  []
]

```

</p></details>

<details><summary>Dividendengutschrift1.pdf</summary><p>

```json
[
  []
]

```

</p></details>

<details><summary>Wertpapierabrechnung_Kauf.pdf</summary><p>

```json
[
  []
]

```

</p></details>

<details><summary>Wertpapierabrechnung_Verkauf.pdf</summary><p>

```json
[
  [],
  []
]

```

</p></details>

---
Issue submitted with https://import.tresor.one

**Comment by dredav** [comment]
All documents are empty. Can't contact the user. Closed.
