### ISSUE TITLE
Performance? WTF??!

### ISSUE THREAD

**Issue by MaxMihawk** [tresorone/tresor-import#3294]
![grafik](https://user-images.githubusercontent.com/19865256/123866459-61a6a900-d92d-11eb-8863-ce9f0c2b74ef.png)

Eure Basisdaten stimmen nicht. Das zerhagelt den ganzen Chart.

Ich tippe mal auf die Rohdaten von **SPDR S&P US Dividend Aristocrats UCITS ETF - USD DIS** Mitte 2017 (ohne Gewähr).

**Comment by dredav** [comment]
Hallo @MaxMihawk. Hier im Repository geht es "nur" den Import selbst. Wende dich via Community direkt an [Julian](https://community.tresor.one/u/eb8f05fa) - er arbeitet gerade an dem Performance-Chart und kann sich das Problem genauer anschauen.
