### ISSUE TITLE
[Flatex] Datei kann nicht importiert werden

### ISSUE THREAD

**Issue by codeofsumit** [tresorone/tresor-import#3535]
## Description
> Datei kann nicht importiert werden

## Document
<details><summary>Transaktionen.pdf</summary><p>

```json
[
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
  []
]

```

</p></details>

## Community profile

https://app.parqet.com/p/60f7cfacb67f520038c8c89a

---
Issue submitted with https://import.parqet.com

**Comment by JohnBra** [comment]
@dredav File is empty. Issue may be closed.
