### ISSUE TITLE
Fixing import issues (e. g. #3678) and working on other issues

### ISSUE THREAD

**Issue by JohnBra** [tresorone/tresor-import#3682]
Hey @dredav,

I had a talk with sumit yesterday (my yesterday) about fixing import issues and generally helping you out with the import package. Environment is set up on my side and I have already looked through some issues. Specifically I have been looking at #3678, which is one of the more recent flatex issues.

My approach would be to import the provided json as a mock file. As it is a mixed PDF I would add it in the 'mixed-pages' dir. My next step would be writing out tests for the expected mapping [here](https://github.com/tresorone/tresor-import/blob/master/tests/brokers/flatex.test.js#L511-L556) and then running the tests and look for errors. Does that sound about right, or is there a better/faster/smarter approach to finding the errors?

Regarding work on issues, that aren't auto generated or high priority features/refactoring/testing just let me know where I can help.

Best
John

**Comment by dredav** [comment]
Hi @JohnBra,

sorry for my late respone.
Thanks for contributing. Fixing flatex is fine for me.

The workflow for fixing issues / adding more support can be done on two ways (or one, combined).
1. Web based: run `npm run demo` and go to `localhost:5000`. There you can upload pdf documents or insert the json mock files. Errors should be visible at the developer console.
2. Test based: Add a mock files from the issue, write a test case and then adjust the broker implementation to get the test parsed.

Both ways are working. But: I've check each issue first at the demo and then decide to write a test or not. Most issues are valid (the import dosen't for the user) but the reason behind is a not valid document (trade republich with crypro which will support in the furture but not yet, cost information documents, other not trade related document, ...).
When I found a issue I will work on, I search all issues which are related to the broker (e.g. [flatex](https://github.com/tresorone/tresor-import/issues?q=is%3Aissue+is%3Aopen+flatex) and check all/some of them)

For each PR (which fix one or more issue) we need a test with the mock file. Then fixing multiple issues with the same problem, adding only one mockfile is fine (e.g #3676 will fix 7+ issues but only 4 different mocks was added).

Best
David

**Comment by JohnBra** [comment]
Thanks @dredav for the through reply.

After I have worked through this issue, I would like to focus on Trade Republic and Comdirect, as those comprise the majority of the user base. Would that be alright with you?
